### ISSUE TITLE
campo pesquisa

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#10]
Criar um campo pesquisa para selecionar estagiário na tela "Realiza Serviços"

**Comment by rodrigofaria** [comment]
Qual tela é essa ?

**Comment by decomartins** [comment]
A ideia dessa tela era no inicio buscar um estagiário, pois ia chegar um tempo que ia ter muito estagiários cadastrados, porem isso ja foi resolvido, no momento em que vc deixou somente os estagiários ativos aparecer para a seleção

vou fechar essa issue
