### ISSUE TITLE
Desativar estagiário

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#13]
Desativar o estagiário da lista quando ele terminar o tempo de estágio

**Comment by rrocharoberto** [comment]
Foram feitas 3 coisas:
- o estagiário desativado não aparece no combo do paciente
- o estagiário desativado fica em cor laranja na listagem de estagiários
- o estagiário desativado não visualiza seus pacientes. É mostrada uma mensagem no lugar.

**Comment by decomartins** [comment]
implementado
