### ISSUE TITLE
Relatorio básicos

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#25]
Relatorios relacionados ao cadastro:
Estagiarios (listar os estagiários que cada professora está orientando)
Professores (listar os professores com seus estagiários)
Lista de espera (listar quem está na lista de espera, por ordem alfabética e cronológica)
Pacientes em tratamento (listar os pacientes em tratamento e qual estagiário está atendendo)

**Comment by rrocharoberto** [comment]
O relatório com os pacientes na fila de espera.
