### ISSUE TITLE
colocar para aparecer a área do serviço no cadastro do professor

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#26]
No momento de cadastro do professora, não está aparecendo a área do serviço e sim somente o sub-serviço, porem tem alguns serviços que não tem sub-serviço e assim será preciso selecionar a área do serviço.

**Comment by rrocharoberto** [comment]
Quando um serviço não tiver sub-serviço, precisa cadastrar um sub-serviço com o mesmo nome do serviço.
