### ISSUE TITLE
estágiario nao está aparecendo na tela do professor

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#27]
Não está aparecendo para o professor os estagiarios que ele está supervisionando. este procedimento é necessário para o professor validar a evolução dos atendimentos

**Comment by rrocharoberto** [comment]
Precisa criar uma tela específica para mostrar os estagiários/evolução adequadamente para o professor (separado da tela de evolução do estagiário).

**Comment by decomartins** [comment]
realizado com sucesso
