### ISSUE TITLE
criar uma local para associar um estagiário ao serviço

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#3]
Criar um local para associar o estagiário ao serviço e ao paciente

**Comment by rrocharoberto** [comment]
Esta operação é feita através do menu *Realiza Serviço*.
Precisa confirmar se este menu vai ficar lá mesmo ou vai ter uma lista de estagiários com um botão (na linha de cada estagiário) para fazer a associação.

**Comment by decomartins** [comment]
realizado com sucesso
