### ISSUE TITLE
mostrar dados do paciente na tela de validação do professor

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#45]
Mostrar para o professor os dados do paciente que ele está validando

**Comment by rodrigofaria** [comment]
Em qual tela?

**Comment by decomartins** [comment]
Na tela de validação do professor.

Obs: No momento em que o professor vai validar a evolução realizada por alguns estagiário.
Ele clica em validar. nesse momento deve aparecer os dados do paciente do qual o professor está validando a evolução

**Comment by rodrigofaria** [comment]
Done!
