### ISSUE TITLE
evolução não responde

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#5]
Na tela de evolução os botões nem o campo respondem

**Comment by rrocharoberto** [comment]
Ele está funcionando (navegando e salvando no banco).
Porém a última tela continua na mesma.
Precisa definir para qual tela deve ir depois.

**Comment by rrocharoberto** [comment]
Por enquanto aparece apenas os pacientes do estagiário 999999999.

**Comment by decomartins** [comment]
realizado com sucesso
