### ISSUE TITLE
Verificar se o CPF já existe quando cadastrar uma nova pessoa

### ISSUE THREAD

**Issue by rrocharoberto** [rrocharoberto/psi#6]
Fazer a validação logo após a digitação do cpf (para paciente, funcionário, estagiário e professor)

**Comment by rrocharoberto** [comment]
Agora faz mais sentido validar a duplicidade do número do prontuário.

**Comment by rrocharoberto** [comment]
André, o número do prontuário vai poder ser editado após salvar um paciente novo no sistema?

**Comment by decomartins** [comment]
Verificar com a Regiane/Alaíde
