### ISSUE TITLE
cadastro de fila de espera

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#7]
Precisa fazer um cadastro de fila de espera com os campos
Fila de espera:
Cadastro:
Nome
Data Nascimento
Data Entrada
Telefone

Esse é a primeira tela a ser utilizada pelo funcionário para cadastro no sistema, ela faz um pre cadastro do paciente com os dados acima, que quando ele for chamada, é feito o cadastro completo e o encaminhamento para o tratamento.

**Comment by rrocharoberto** [comment]
Precisa criar uma tabela nova. Deve ter um campo para indicar desistência ou encaminhamento.

**Comment by decomartins** [comment]
realizado com sucesso
