### ISSUE TITLE
Gerar prontuario

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#8]
Gerar o prontuário, para que depois o paciente seja referenciado a ele, pois o prontuário é o identificador dos acompanhamentos:

ex: prontuario 10. quando chamado vai trazer o paciente, o estagiário o serviço. para a realização do acompanhamento.

**Comment by rrocharoberto** [comment]
Acho que é bom incluir a data de criação do prontuário no banco.

**Comment by decomartins** [comment]
é uma boa

**Comment by decomartins** [comment]
realizado com sucesso
