### ISSUE TITLE
acompanhamento

### ISSUE THREAD

**Issue by decomartins** [rrocharoberto/psi#9]
nesta tela deve colocar o prontuário, para que o usuário possa digitar, o numero, ou pesquisar pelo nome do paciente e encontrar o prontuário para a realização do acompanhamento.

**Comment by rrocharoberto** [comment]
A tela de evolução faz +- isso. Busca o paciente, depois o serviço e depois entra com os dados de evolução.

**Comment by decomartins** [comment]
feito
